### PR TITLE
Update MP-Heaters.adoc

### PR DESCRIPTION
**Pull request by mrhid6**

### CODE REVIEW

**Review by mrhid6 — COMMENTED** [review]
These numbers dont seam correct with the current version sure your on the correct version (2.1.7)?

**Comment by mrhid6** [comment]
@razor64 Please see comment above ^^

**Comment by razor64** [comment]
I am on version 2.1.7 and spent few hours testing so I'm pretty sure :)

**Comment by trunkyredstone** [comment]
I have a feeling that these numbers are being affected by a slow tick rate. Did you get these numbers from a big world, or a new world?

**Comment by mrhid6** [comment]
@razor64 ?

**Comment by nbrugger-tgm** [comment]
Whaaait does that mean the flow/production/consumption is dependent on the Frame and tick-rate or the Hardware?

**Pull request closed without merging**
